import type {
  BackgroundDef,
  ClassDef,
  RaceDef,
  SkillId,
  Spell,
} from "./types";

export const RACES: RaceDef[] = [
  {
    id: "human",
    name: "人类",
    size: "中型",
    speed: 30,
    summary: "适应性极强。全属性 +1，额外掌握一项技能。",
    bonuses: "all1",
    extraSkills: 1,
    traits: ["额外语言一门", "多才多艺：从技能表再选一项熟练（已计入人物卡）"],
  },
  {
    id: "high-elf",
    name: "高精灵",
    size: "中型",
    speed: 30,
    summary: "敏捷 +2、智力 +1。黑暗视觉，戏法，武器训练。",
    bonuses: { dex: 2, int: 1 },
    extraCantrip: true,
    traits: [
      "黑暗视觉 60 尺：微光当明亮，黑暗当微光",
      "妖精血统：对抗魅惑的豁免具有优势；魔法无法让你睡眠",
      "出神：长休 4 小时冥想即可，期间仍有察觉",
      "精灵武器熟练：长剑、短剑、短弓、长弓",
      "高精灵戏法：自选一个法师戏法，用智力施放",
    ],
  },
  {
    id: "wood-elf",
    name: "木精灵",
    size: "中型",
    speed: 35,
    summary: "敏捷 +2、感知 +1。掩藏于荒野，脚步无声。",
    bonuses: { dex: 2, wis: 1 },
    traits: [
      "黑暗视觉 60 尺",
      "妖精血统：魅惑豁免优势，魔法睡眠无效",
      "出神：4 小时冥想视为长休",
      "野性蒙面：轻遮掩（雨、落叶、雾）中可尝试躲藏",
      "精灵武器熟练：长剑、短剑、短弓、长弓",
    ],
  },
  {
    id: "hill-dwarf",
    name: "丘陵矮人",
    size: "中型",
    speed: 25,
    summary: "体质 +2、感知 +1。每级额外生命，坚如磐石。",
    bonuses: { con: 2, wis: 1 },
    traits: [
      "黑暗视觉 60 尺",
      "矮人韧性：毒素伤害抗性；对抗中毒的豁免优势",
      "矮人坚韧：每级生命值＋1（已计入）",
      "石窟记忆：石造起源的智力（历史）检定有优势",
      "战斗斧与战锤熟练",
    ],
  },
  {
    id: "mountain-dwarf",
    name: "山地矮人",
    size: "中型",
    speed: 25,
    summary: "力量 +2、体质 +2。天生披甲。",
    bonuses: { str: 2, con: 2 },
    traits: [
      "黑暗视觉 60 尺",
      "矮人韧性：毒素抗性，中毒豁免优势",
      "着甲训练：轻甲与中甲熟练",
      "石窟记忆：石造起源的智力（历史）优势",
    ],
  },
  {
    id: "lightfoot",
    name: "轻足半身人",
    size: "小型",
    speed: 25,
    summary: "敏捷 +2、魅力 +1。幸运、勇敢，可躲在队友身后。",
    bonuses: { dex: 2, cha: 1 },
    traits: [
      "幸运：攻击、检定或豁免的 d20 出 1，可重掷，必须用新结果。不耗资源，出 1 时 KP 应提醒",
      "勇敢：对抗恐慌的豁免具有优势",
      "半身人灵巧：可穿过任何比你体型大的生物所占空间",
      "天生隐匿：可尝试躲在中型或更大的盟友身后",
    ],
  },
  {
    id: "dragonborn",
    name: "龙裔",
    size: "中型",
    speed: 30,
    summary: "力量 +2、魅力 +1。吐息武器与伤害抗性。",
    bonuses: { str: 2, cha: 1 },
    traits: [
      "吐息武器：动作，3 级 2d6（对应龙种伤害）。15 尺锥或 30 尺线，豁免 DC＝8＋熟练＋体质。短休后可用",
      "对应伤害类型抗性",
      "龙族血统外貌：鳞片、无翼",
    ],
  },
  {
    id: "half-elf",
    name: "半精灵",
    size: "中型",
    speed: 30,
    summary: "魅力 +2，另两项 +1。两项额外技能。",
    bonuses: "halfElf",
    extraSkills: 2,
    traits: ["黑暗视觉 60 尺", "妖精血统：魅惑豁免优势，魔法睡眠无效", "多才多艺：额外两项技能熟练（已计入）"],
  },
  {
    id: "half-orc",
    name: "半兽人",
    size: "中型",
    speed: 30,
    summary: "力量 +2、体质 +1。濒死仍能站起，暴击更狠。",
    bonuses: { str: 2, con: 1 },
    traits: [
      "黑暗视觉 60 尺",
      "威胁：威吓熟练（若尚未有）",
      "不屈不挠：生命被降至 0 而未即死时，可改为剩 1 点。长休后恢复。不耗法术位",
      "凶蛮攻击：近战武器暴击时，额外再掷一次武器伤害骰并加入",
    ],
  },
  {
    id: "tiefling",
    name: "提夫林",
    size: "中型",
    speed: 30,
    summary: "智力 +1、魅力 +2。火焰抗性，炼狱血统法术。",
    bonuses: { int: 1, cha: 2 },
    traits: [
      "黑暗视觉 60 尺",
      "火焰抗性",
      "炼狱血统：奇术戏法；3 级起每日一次炼狱叱喝（魅力施法，不另占已知法术）",
    ],
  },
];

const ALL_SKILLS: SkillId[] = [
  "athletics",
  "acrobatics",
  "sleight",
  "stealth",
  "arcana",
  "history",
  "investigation",
  "nature",
  "religion",
  "animal",
  "insight",
  "medicine",
  "perception",
  "survival",
  "deception",
  "intimidation",
  "performance",
  "persuasion",
];

export const CLASSES: ClassDef[] = [
  {
    id: "fighter",
    name: "战士",
    hitDie: 10,
    primary: ["str", "dex"],
    saves: ["str", "con"],
    armor: "所有护甲、盾牌",
    weapons: "简易与军用",
    skillPicks: 2,
    skillList: ["acrobatics", "animal", "athletics", "history", "insight", "intimidation", "perception", "survival"],
    summary: "战场的轴心。护甲厚、出手稳，3 级选定武艺道路。",
    features: [
      "战斗风格·防御：着甲时 AC＋1（已计入人物卡）",
      "回气：短休时，用附赠动作花一颗生命骰，恢复该骰＋体质调整生命。3 级有 3 颗 d10 生命骰",
      "动作如潮（2 级，短休 1 次）：你的回合内额外获得一个动作（可攻击、疾走、撤离、躲藏、使用物品等）",
      "3 级子职权能见下",
    ],
    subclasses: [
      {
        id: "champion",
        name: "冠军",
        summary: "暴击范围扩大为 19–20。纯粹的杀戮效率。",
        features: ["精通暴击：使用武器攻击时，d20 出 19 或 20 即为暴击（正常仅 20）"],
      },
      {
        id: "battlemaster",
        name: "战斗大师",
        summary: "战术骰操纵战场。绊摔、推击、还击。",
        features: [
          "战术骰：4 颗 d8，短休或长休后全部恢复",
          "战技（选推击、还击、绊摔等）：攻击命中时花 1 颗战术骰，伤害加上该骰，并施加对应效果。豁免 DC＝8＋熟练＋力量或敏捷调整（较高者）",
        ],
      },
    ],
  },
  {
    id: "barbarian",
    name: "野蛮人",
    hitDie: 12,
    primary: ["str"],
    saves: ["str", "con"],
    armor: "轻甲、中甲、盾牌（无甲防御）",
    weapons: "简易与军用",
    skillPicks: 2,
    skillList: ["animal", "athletics", "intimidation", "nature", "perception", "survival"],
    summary: "以怒火换取伤害与抗性。无甲也能硬扛。",
    features: [
      "狂暴（3 级每日 3 次，附赠动作进入，持续 1 分钟）：力量检定与力量豁免优势；近战力量攻击命中时额外＋2 伤害；钝击/穿刺/挥砍抗性。穿重甲不能狂暴。每回合若未攻击也未受到伤害则可提前结束",
      "无甲防御：未着甲时 AC＝10＋敏捷调整＋体质调整（已计入，若未穿甲）",
      "危险感知：你能看见的陷阱与法术的敏捷豁免具有优势",
      "鲁莽攻击：你的回合近战力量攻击全部有优势，但直至你的下个回合开始，对你的攻击也有优势",
      "3 级子职。狂暴不耗法术位，但有每日次数",
    ],
    subclasses: [
      {
        id: "berserker",
        name: "狂战士",
        summary: "狂暴时可进入狂乱，每回合额外一次近战攻击，结束后力竭。",
        features: [
          "狂乱：进入狂暴时可选择狂乱。狂暴期间每回合可用附赠动作做一次近战武器攻击。狂暴结束后获得一层力竭",
        ],
      },
    ],
  },
  {
    id: "rogue",
    name: "游荡者",
    hitDie: 8,
    primary: ["dex"],
    saves: ["dex", "int"],
    armor: "轻甲",
    weapons: "简易、手弩、长剑、刺剑、短剑",
    skillPicks: 4,
    skillList: ALL_SKILLS,
    summary: "偷袭、巧手、从阴影里把问题解开。",
    features: [
      "专精：两项技能熟练加值翻倍（已在人物卡技能上显示）",
      "偷袭 2d6：每回合一次。用敏捷的攻击检定命中，且你具有优势，或目标 5 尺内有未失能的盟友且你没有劣势时，额外 2d6 伤害",
      "盗贼黑话：黑话暗号",
      "灵巧动作：每回合可用附赠动作疾走、撤离或躲藏。不耗资源",
      "3 级子职",
    ],
    subclasses: [
      {
        id: "thief",
        name: "盗贼",
        summary: "攀爬、偷摸、第二回合就能用好物品。",
        features: [
          "快手：可用附赠动作使用物品（喝药水、投掷沙袋等）",
          "第二层故事：攀爬不额外耗移动；助跑跳远距离加上力量调整值",
        ],
      },
      {
        id: "assassin",
        name: "刺客",
        summary: "突袭轮攻击优势；目标未完成回合则自动暴击。",
        features: [
          "刺客训练：易容工具与下毒工具熟练",
          "刺杀：突袭轮中，对尚未完成回合的生物的攻击检定具有优势；若击中且该生物尚未行动，则该击为暴击",
        ],
      },
    ],
  },
  {
    id: "wizard",
    name: "法师",
    hitDie: 6,
    primary: ["int"],
    saves: ["int", "wis"],
    armor: "无",
    weapons: "匕首、飞镖、投石索、短杖、轻弩",
    skillPicks: 2,
    skillList: ["arcana", "history", "insight", "investigation", "medicine", "religion"],
    summary: "以智力塑形现实。3 级已有二环，法术位 4/2。",
    spellcasting: "wizard",
    features: [
      "法术位：一环 4 个、二环 2 个。长休恢复。戏法不耗位",
      "法术书与准备：准备数＝智力调整＋3。只能准备书中的法术",
      "奥术恢复：每日一次，短休结束时恢复总值不超过 2 的环位（例如一个二环，或两个一环）",
      "2 级选定学派",
    ],
    subclasses: [
      {
        id: "evocation",
        name: "塑能学派",
        summary: "塑能戏法更狠，可以在范围法术中为盟友开洞。",
        features: [
          "塑能塑造：你释放的塑能法术可在范围内为若干盟友开洞，他们自动成功豁免并不受伤害。数量＝1＋法术环级",
          "强力戏法：你的塑能戏法伤害加上智力调整",
        ],
      },
      {
        id: "abjuration",
        name: "防护学派",
        summary: "奥术结界吸收伤害，护住自己与同伴。",
        features: [
          "奥术结界：准备防护学派法术时，获得生命值＝2×法师等级＋智力调整的吸收护盾。结界存在时，对你的每次伤害先扣结界",
        ],
      },
    ],
  },
  {
    id: "cleric",
    name: "牧师",
    hitDie: 8,
    primary: ["wis"],
    saves: ["wis", "cha"],
    armor: "轻甲、中甲、盾牌",
    weapons: "简易",
    skillPicks: 2,
    skillList: ["history", "insight", "medicine", "persuasion", "religion"],
    summary: "神的手。治疗、驱散、领域权能。法术位 4/2。",
    spellcasting: "cleric",
    features: [
      "法术位 一环 4 / 二环 2。准备数＝感知调整＋3。可准备牧师法术表中任意已解锁环的法术",
      "引导神力 1/短休：见领域。驱散亡灵：动作，30 尺内不死做感知豁免，失败则被驱离 1 分钟",
      "戏法不耗环位。神导术在对话/技能检定面板勾选，掷出才生效，不要口头再问一轮",
      "1 级领域，3 级领域强化",
    ],
    subclasses: [
      {
        id: "life",
        name: "生命领域",
        summary: "重甲、治疗法术额外生命，引导神力为众人疗伤。",
        features: [
          "重甲熟练",
          "生命领域弟子：你释放的一环及以上治疗法术，额外恢复 2＋该法术环级生命",
          "引导神力·维持生命：动作，治疗 5×牧师等级生命，可分给 30 尺内若干生物（各至少 1 点）。短休恢复",
        ],
      },
      {
        id: "war",
        name: "战争领域",
        summary: "军用武器与重甲。战争牧师能把祈祷变成刀锋。",
        features: [
          "重甲与军用武器熟练",
          "战争祭司：每回合一次，当你用动作做武器攻击时，可用附赠动作再攻击一次。每日次数＝感知调整（至少 1），长休恢复",
          "引导神力·导向打击：攻击命中后可用，该次攻击伤害额外＋10。短休恢复",
        ],
      },
      {
        id: "knowledge",
        name: "知识领域",
        summary: "两项知识技能双倍熟练，学识就是神迹。",
        features: [
          "两项智力技能（奥秘/历史/自然/调查/宗教）熟练并专精（双倍熟练）",
          "领域法术始终准备且不计入准备数：鉴定术、命令术、暗示术、卜筮术（3 级已有一环与二环）",
        ],
      },
    ],
  },
  {
    id: "ranger",
    name: "游侠",
    hitDie: 10,
    primary: ["dex", "wis"],
    saves: ["str", "dex"],
    armor: "轻甲、中甲、盾牌",
    weapons: "简易与军用",
    skillPicks: 3,
    skillList: ["animal", "athletics", "insight", "investigation", "nature", "perception", "stealth", "survival"],
    summary: "猎手与斥候。3 级获得法术与猎人道途。",
    spellcasting: "ranger",
    features: [
      "宿敌：对选定类型的智力（调查）与感知（求生）追踪检定有优势，并多懂一门相关语言",
      "自然探索者：在选定地形中困难地形不减速，且群体旅行时相关检定更稳",
      "战斗风格·射术：使用远程武器进行攻击检定时获得＋2；长射程仍依 2014 规则承受劣势",
      "3 级法术：已知 3 个一环，法术位 3。感知施法",
    ],
    subclasses: [
      {
        id: "hunter",
        name: "猎人",
        summary: "巨兽克星或集群克星，专打大的或专打一群。",
        features: [
          "猎人之猎物（二选一，每次长休可改）：巨兽克星——你用武器攻击命中大型或更大的生物时额外 1d8；集群克星——用动作攻击后，可对 5 尺内另一生物用同一武器再攻击一次",
        ],
      },
    ],
  },
];

export const BACKGROUNDS: BackgroundDef[] = [
  {
    id: "acolyte",
    name: "侍僧",
    skills: ["insight", "religion"],
    tools: "两门额外语言",
    summary: "在神殿长大，识得仪式与圣徽。",
    equipment: ["圣徽", "祈祷书", "香烛", "普通衣服", "15 gp"],
  },
  {
    id: "criminal",
    name: "罪犯",
    skills: ["deception", "stealth"],
    tools: "盗贼工具、一种赌具",
    summary: "认识地下通道和该闭嘴的时候。",
    equipment: ["撬棍", "暗袋", "普通衣服", "15 gp"],
  },
  {
    id: "soldier",
    name: "士兵",
    skills: ["athletics", "intimidation"],
    tools: "一种赌具、陆载载具",
    summary: "编制、口令、战场纪律还留在骨头里。",
    equipment: ["军衔徽记", "战利品", "普通衣服", "10 gp"],
  },
  {
    id: "sage",
    name: "学者",
    skills: ["arcana", "history"],
    tools: "两门额外语言",
    summary: "图书馆比酒馆更像家。",
    equipment: ["墨水与笔", "小刀", "书信", "普通衣服", "10 gp"],
  },
  {
    id: "folk",
    name: "民兵/旅人",
    skills: ["animal", "survival"],
    tools: "一种乐器、陆载载具",
    summary: "识得天气、牲口和哪条路夜里不能走。",
    equipment: ["手杖", "铁锅", "铁质器皿", "普通衣服", "10 gp"],
  },
  {
    id: "noble",
    name: "贵族",
    skills: ["history", "persuasion"],
    tools: "一种赌具、一门额外语言",
    summary: "纹章能开门，也能把刀引到背上。",
    equipment: ["细服", "印章戒指", "族谱卷", "25 gp"],
  },
  {
    id: "sailor",
    name: "水手",
    skills: ["athletics", "perception"],
    tools: "导航工具、水载载具",
    summary: "绳结、潮汐、以及哪间酒馆不打水手。",
    equipment: ["短棍", "绳 50 尺", "幸运符", "普通衣服", "10 gp"],
  },
  {
    id: "urchin",
    name: "流浪儿",
    skills: ["sleight", "stealth"],
    tools: "易容工具、盗贼工具",
    summary: "城市的缝是你走的路。",
    equipment: ["小刀", "地图残片", "宠物鼠", "普通衣服", "10 gp"],
  },
];

export const SPELLS: Spell[] = [
  {
    id: "light",
    name: "光亮术",
    level: 0,
    school: "塑能",
    time: "动作",
    range: "触碰",
    duration: "1 小时",
    text: "触碰一个物体（体积不大于 10 尺）。它发出 20 尺明亮光照，再向外 20 尺微光。可用动作提前结束。遮盖光源则光照被挡住。不耗法术位。",
  },
  {
    id: "prestidigitation",
    name: "魔法伎俩",
    level: 0,
    school: "变化",
    time: "动作",
    range: "10 尺",
    duration: "至多 1 小时",
    text: "同时维持最多三个无害小效果：点燃/熄灭蜡烛，弄脏或清洁 1 立方尺，温热或冰镇非活物 1 小时，留下标记或气味，弄出火花或气味。不能造成伤害或直接开锁。不耗法术位。",
  },
  {
    id: "mage-hand",
    name: "法师之手",
    level: 0,
    school: "咒法",
    time: "动作",
    range: "30 尺",
    duration: "1 分钟",
    text: "唤出一只幽灵手。用动作让它在 30 尺内移动、开关未锁容器、取放物品、倒出瓶壶。负重不超过 10 磅。不能攻击、不能启动魔法物品、不能提超过 10 磅的东西。不耗法术位。",
  },
  {
    id: "fire-bolt",
    name: "火焰箭",
    level: 0,
    school: "塑能",
    time: "动作",
    range: "120 尺",
    duration: "即效",
    text: "对你能看见的目标做远程法术攻击。命中造成 1d10 火焰伤害（3 级仍为 1d10）。可点燃未被着装或携带的易燃物。不耗法术位。",
  },
  {
    id: "ray-frost",
    name: "冷冻射线",
    level: 0,
    school: "塑能",
    time: "动作",
    range: "60 尺",
    duration: "即效",
    text: "远程法术攻击。命中造成 1d8 冷冻伤害，且目标速度直至你的下个回合开始前减少 10 尺。不耗法术位。",
  },
  {
    id: "shocking",
    name: "电爪",
    level: 0,
    school: "塑能",
    time: "动作",
    range: "触碰",
    duration: "即效",
    text: "近战法术攻击。命中造成 1d8 闪电伤害，目标直至其下个回合开始不能做反应（不能借机攻击、不能释放护盾术）。不耗法术位。",
  },
  {
    id: "minor-illusion",
    name: "次级幻象",
    level: 0,
    school: "幻术",
    time: "动作",
    range: "30 尺",
    duration: "1 分钟",
    text: "造出声音（至多如说话音量）或静止影像（5 尺立方）。影像不可产生光、气味或温度。生物用动作调查（智力（调查）对抗你的法术豁免 DC）可看穿，此后对它变为半透明。不耗法术位。",
  },
  {
    id: "guidance",
    name: "神导术",
    level: 0,
    school: "预言",
    time: "动作",
    range: "触碰",
    duration: "专注，至多 1 分钟",
    askOn: "check",
    text: "触碰一个自愿生物。在持续时间内，它进行一次属性检定（含技能）前，可额外掷 1d4 加在结果上，然后法术结束。不耗法术位。对话和技能检定由面板勾选，勾了并掷出才加；不要再口头问一轮。",
  },
  {
    id: "sacred-flame",
    name: "神圣火焰",
    level: 0,
    school: "塑能",
    time: "动作",
    range: "60 尺",
    duration: "即效",
    text: "目标必须通过敏捷豁免，失败则受 1d8 光耀伤害。全遮掩不给此次豁免优势——火焰自天而降。不耗法术位。",
  },
  {
    id: "thaumaturgy",
    name: "奇术",
    level: 0,
    school: "变化",
    time: "动作",
    range: "30 尺",
    duration: "至多 1 分钟",
    text: "同时最多三个：嗓音响至三倍；火焰明灭变色；大地震颤（不造成伤害）；瞬间开门窗；自己的眼睛变色。用于唬人、仪式、吓人。不耗法术位。",
  },
  {
    id: "spare",
    name: "维生术",
    level: 0,
    school: "死灵",
    time: "动作",
    range: "触碰",
    duration: "即效",
    askOn: "dying",
    text: "触碰一个生命值为 0、仍活着的生物，使其伤势稳定（不再死亡豁免）。不恢复生命。不耗法术位。有人倒下时必须询问是否使用。",
  },
  {
    id: "mage-armor",
    name: "法师护甲",
    level: 1,
    school: "防护",
    time: "动作",
    range: "触碰",
    duration: "8 小时",
    text: "未着甲的自愿生物 AC 变成 13＋敏捷调整值，持续 8 小时，或直到穿上护甲。耗 1 环。",
  },
  {
    id: "shield",
    name: "护盾术",
    level: 1,
    school: "防护",
    time: "反应（被击中或遭魔法飞弹时）",
    range: "自身",
    duration: "至你的下个回合开始",
    askOn: "hit",
    text: "被攻击命中、或成为魔法飞弹目标时可用。AC＋5 直到你的下个回合开始，并免疫魔法飞弹。耗 1 环。被打中时应询问是否消耗环位释放。",
  },
  {
    id: "magic-missile",
    name: "魔法飞弹",
    level: 1,
    school: "塑能",
    time: "动作",
    range: "120 尺",
    duration: "即效",
    text: "三发闪光飞弹，各自动命中你能看见的生物，每发 1d4＋1 力场。可打同一人或分开。盾术可挡下全部。耗 1 环。",
  },
  {
    id: "sleep",
    name: "睡眠术",
    level: 1,
    school: "惑控",
    time: "动作",
    range: "90 尺",
    duration: "1 分钟",
    text: "20 尺半径内，从当前生命最低的生物开始，累计 5d8 生命值的生物陷入昏迷（不免疫睡眠者才有效）。不受伤或被摇醒则醒来。对不死无效。耗 1 环。",
  },
  {
    id: "detect-magic",
    name: "侦测魔法",
    level: 1,
    school: "预言",
    time: "动作（可仪式）",
    range: "自身",
    duration: "专注，至多 10 分钟",
    text: "感知 30 尺内魔法的存在。能看见微弱灵光并辨认学派。1 尺障碍、1 寸金属、薄铅皮会挡住。仪式可不耗环位，但多花 10 分钟。",
  },
  {
    id: "identify",
    name: "鉴定术",
    level: 1,
    school: "预言",
    time: "1 分钟（可仪式）",
    range: "触碰",
    duration: "即效",
    text: "触碰一件魔法物品或生物，得知其魔法属性、使用方式、所需同调。仪式可不耗环位。",
  },
  {
    id: "charm",
    name: "魅惑人类",
    level: 1,
    school: "惑控",
    time: "动作",
    range: "30 尺",
    duration: "1 小时",
    text: "一个类人生物做感知豁免（战斗中有优势）。失败则视你为友善熟人，不会听命自杀。你或同伴伤害它则结束。结束后它知道被魅惑过。耗 1 环。",
  },
  {
    id: "disguise",
    name: "易容术",
    level: 1,
    school: "幻术",
    time: "动作",
    range: "自身",
    duration: "1 小时",
    text: "改变外貌与衣着，含身高体型在 1 尺内。不改变声音、也不提供新能力。有人触碰或调查可用智力（调查）对抗你的法术 DC。耗 1 环。",
  },
  {
    id: "thunderwave",
    name: "雷鸣波",
    level: 1,
    school: "塑能",
    time: "动作",
    range: "自身（15 尺立方）",
    duration: "即效",
    text: "自身出发 15 尺立方。其中生物做体质豁免：失败受 2d8 雷鸣并被推开 10 尺；成功伤害减半且不推开。300 尺内可听见。耗 1 环。",
  },
  {
    id: "burning-hands",
    name: "燃烧之手",
    level: 1,
    school: "塑能",
    time: "动作",
    range: "自身（15 尺锥状）",
    duration: "即效",
    text: "15 尺锥状火焰。敏捷豁免失败受 3d6 火焰，成功减半。可点燃未被着装的易燃物。耗 1 环。",
  },
  {
    id: "healing-word",
    name: "治愈真言",
    level: 1,
    school: "塑能",
    time: "附赠动作",
    range: "60 尺",
    duration: "即效",
    text: "你能看见的一个生物恢复 1d4＋感知调整生命。对不死与构装无效。可把 0 生命的人拉起来。耗 1 环。",
  },
  {
    id: "cure",
    name: "治愈伤口",
    level: 1,
    school: "塑能",
    time: "动作",
    range: "触碰",
    duration: "即效",
    text: "触碰一个生物，恢复 1d8＋施法关键属性调整生命。对不死与构装无效。耗 1 环。",
  },
  {
    id: "bless",
    name: "祝福术",
    level: 1,
    school: "惑控",
    time: "动作",
    range: "30 尺",
    duration: "专注，至多 1 分钟",
    text: "最多三个你能看见的生物，在攻击检定和豁免检定时额外加 1d4。耗 1 环。不用于属性检定（那是神导术的事）。鉴定若是攻击或豁免，必须问是否已祝福。",
  },
  {
    id: "guiding-bolt",
    name: "光导箭",
    level: 1,
    school: "塑能",
    time: "动作",
    range: "120 尺",
    duration: "1 轮",
    text: "远程法术攻击，命中造成 4d6 光耀。直到你的下个回合结束，下一次对该目标的攻击检定具有优势。耗 1 环。",
  },
  {
    id: "inflict",
    name: "致伤术",
    level: 1,
    school: "死灵",
    time: "动作",
    range: "触碰",
    duration: "即效",
    text: "近战法术攻击，命中造成 3d10 暗蚀伤害。耗 1 环。",
  },
  {
    id: "shield-faith",
    name: "虔诚护盾",
    level: 1,
    school: "防护",
    time: "附赠动作",
    range: "60 尺",
    duration: "专注，至多 10 分钟",
    text: "一个你能看见的生物获得＋2 AC。耗 1 环。",
  },
  {
    id: "command",
    name: "命令术",
    level: 1,
    school: "惑控",
    time: "动作",
    range: "60 尺",
    duration: "1 轮",
    text: "对一个能听懂你语言、非不死的生物说一个词：过来、放下、停下、逃走、趴下。感知豁免失败则在其下个回合执行。直接有害的命令会被忽略。耗 1 环。",
  },
  {
    id: "detect-evil",
    name: "侦测善恶",
    level: 1,
    school: "预言",
    time: "动作",
    range: "自身",
    duration: "专注，至多 10 分钟",
    text: "感知 30 尺内的异界生物、不死、以及被祝圣/亵渎的地点或物件。障碍物规则同侦测魔法。耗 1 环。",
  },
  {
    id: "hunters-mark",
    name: "猎人印记",
    level: 1,
    school: "预言",
    time: "附赠动作",
    range: "90 尺",
    duration: "专注，至多 1 小时",
    text: "标记一个你能看见的生物。你用武器攻击命中它时额外 1d6 伤害；寻找它的感知（求生）与感知（察觉）检定具有优势。它死后可用附赠动作转移印记。耗 1 环。",
  },
  {
    id: "goodberry",
    name: "神莓术",
    level: 1,
    school: "变化",
    time: "动作",
    range: "触碰",
    duration: "24 小时",
    text: "在你手中出现十颗莓果。用动作吃一颗：恢复 1 生命，并提供一天所需的营养。24 小时后失去效力。耗 1 环。",
  },
  {
    id: "ensnaring",
    name: "诱捕打击",
    level: 1,
    school: "咒法",
    time: "附赠动作",
    range: "自身",
    duration: "专注，至多 1 分钟",
    text: "下一次武器攻击命中时，目标被荆棘缠绕。大型或更小者做力量豁免，失败则束缚。每回合开始受 1d6 穿刺，用动作力量检定可挣脱。耗 1 环。",
  },
  {
    id: "fog",
    name: "云雾术",
    level: 1,
    school: "咒法",
    time: "动作",
    range: "120 尺",
    duration: "专注，至多 1 小时",
    text: "20 尺半径、20 尺高的浓雾，其中为重度遮掩。风可吹散。耗 1 环。",
  },
  {
    id: "speak-animals",
    name: "动物交谈",
    level: 1,
    school: "预言",
    time: "动作（可仪式）",
    range: "自身",
    duration: "10 分钟",
    text: "理解并口头与野兽交谈。智力仍是野兽的智力，不会让它更友好，但可用魅力检定影响它。仪式可不耗环位。",
  },
  {
    id: "misty",
    name: "迷踪步",
    level: 2,
    school: "咒法",
    time: "附赠动作",
    range: "自身",
    duration: "即效",
    text: "传送到 30 尺内你能看见的未占据空间。耗 2 环。",
  },
  {
    id: "scorching",
    name: "灼热射线",
    level: 2,
    school: "塑能",
    time: "动作",
    range: "120 尺",
    duration: "即效",
    text: "三条火焰射线，各对你能看见的目标做远程法术攻击，命中 2d6 火焰。可打同一人或分开。耗 2 环。",
  },
  {
    id: "hold-person",
    name: "人类定身术",
    level: 2,
    school: "惑控",
    time: "动作",
    range: "60 尺",
    duration: "专注，至多 1 分钟",
    text: "一个你能看见的类人生物做感知豁免，失败则麻痹。每回合结束可再豁免。耗 2 环。",
  },
  {
    id: "invisibility",
    name: "隐形术",
    level: 2,
    school: "幻术",
    time: "动作",
    range: "触碰",
    duration: "专注，至多 1 小时",
    text: "触碰的生物及其着装变为隐形。它攻击或施法时结束。耗 2 环。",
  },
  {
    id: "mirror-image",
    name: "镜影术",
    level: 2,
    school: "幻术",
    time: "动作",
    range: "自身",
    duration: "1 分钟",
    text: "三具分身。攻击你时先掷 d20：三具需 6＋、两具 8＋、一具 11＋才打到分身。分身 AC＝10＋你的敏捷调整，命中即消失。范围效果仍打到你。耗 2 环。",
  },
  {
    id: "web",
    name: "蛛网术",
    level: 2,
    school: "咒法",
    time: "动作",
    range: "60 尺",
    duration: "专注，至多 1 小时",
    text: "20 尺立方黏网，困难地形。生物进入或开始回合在其中须做敏捷豁免，失败则束缚。用动作做力量检定可挣脱。网可被火烧。耗 2 环。",
  },
  {
    id: "spiritual",
    name: "灵体武器",
    level: 2,
    school: "塑能",
    time: "附赠动作",
    range: "60 尺",
    duration: "1 分钟",
    text: "一把力场武器出现。出现时做近战法术攻击，命中 1d8＋感知调整力场伤害。之后每回合可用附赠动作移动它至多 20 尺并再攻击。耗 2 环。",
  },
  {
    id: "aid",
    name: "援助术",
    level: 2,
    school: "防护",
    time: "动作",
    range: "30 尺",
    duration: "8 小时",
    text: "最多三个生物当前生命与最大生命各＋5，持续 8 小时。耗 2 环。",
  },
  {
    id: "lesser-restoration",
    name: "次等复原术",
    level: 2,
    school: "防护",
    time: "动作",
    range: "触碰",
    duration: "即效",
    text: "结束目标身上一项疾病，或目盲、耳聋、麻痹、中毒之一。耗 2 环。",
  },
  {
    id: "silence",
    name: "沉默术",
    level: 2,
    school: "幻术",
    time: "动作（可仪式）",
    range: "120 尺",
    duration: "专注，至多 10 分钟",
    text: "20 尺半径内无声。其中的生物耳聋，语言法术无法施放。仪式可不耗环位。",
  },
  {
    id: "prayer",
    name: "治疗祈祷",
    level: 2,
    school: "塑能",
    time: "动作",
    range: "30 尺",
    duration: "即效",
    text: "最多六个你能看见的生物各恢复 2d8＋感知调整生命。对不死与构装无效。耗 2 环。",
  },
];

export const WIZARD_CANTRIPS = ["fire-bolt", "ray-frost", "shocking", "mage-hand", "prestidigitation", "light", "minor-illusion"];
export const WIZARD_SPELLS = ["mage-armor", "shield", "magic-missile", "sleep", "detect-magic", "identify", "charm", "thunderwave", "burning-hands", "misty", "scorching", "invisibility", "mirror-image", "web", "hold-person"];
export const CLERIC_CANTRIPS = ["guidance", "sacred-flame", "thaumaturgy", "spare", "light"];
export const CLERIC_SPELLS = ["bless", "cure", "healing-word", "guiding-bolt", "inflict", "shield-faith", "command", "detect-evil", "detect-magic", "spiritual", "aid", "lesser-restoration", "silence", "hold-person"];
export const RANGER_SPELLS = ["hunters-mark", "goodberry", "ensnaring", "fog", "speak-animals", "cure"];

export const CLASS_KITS: Record<string, string[][]> = {
  fighter: [
    ["链甲", "长剑", "盾牌", "轻弩与 20 矢", "探险者套装"],
    ["皮甲", "两把短剑", "长弓与 20 矢", "探险者套装"],
  ],
  barbarian: [
    ["巨斧", "两把手斧", "标枪 4 支", "探险者套装"],
    ["巨剑", "手斧两把", "标枪 4 支", "探险者套装"],
  ],
  rogue: [
    ["刺剑", "短弓与 20 矢", "盗贼工具", "皮甲", "撬棍", "盗贼套装"],
    ["短剑两把", "皮甲", "盗贼工具", "盗贼套装"],
  ],
  wizard: [
    ["法术书", "奥术法器（杖）", "匕首", "学者套装", "瓶装墨水"],
    ["法术书", "奥术法器（宝珠）", "轻弩", "探险者套装"],
  ],
  cleric: [
    ["链甲", "盾牌", "钉头锤", "圣徽", "牧师套装"],
    ["鳞甲", "盾牌", "战锤", "圣徽", "探险者套装"],
  ],
  ranger: [
    ["鳞甲", "两把短剑", "长弓与 20 矢", "探险者套装"],
    ["皮甲", "短剑", "长弓与 20 矢", "探险者套装"],
  ],
};

export function raceById(id: string) {
  return RACES.find((r) => r.id === id);
}
export function classById(id: string) {
  return CLASSES.find((c) => c.id === id);
}
export function backgroundById(id: string) {
  return BACKGROUNDS.find((b) => b.id === id);
}
export function spellById(id: string) {
  return SPELLS.find((s) => s.id === id);
}

export function uniqueSpellIds(sheet: {
  cantrips: string[];
  prepared: string[];
  spellbook: string[];
}) {
  return [...new Set([...sheet.cantrips, ...sheet.prepared, ...sheet.spellbook])];
}

/** Free / reaction tools the KP must offer instead of assuming they go unused. */
export function listFreeBoosts(sheet: {
  raceId: string;
  classId: string;
  subclassId?: string;
  cantrips: string[];
  prepared: string[];
  spellbook: string[];
  name: string;
}) {
  const out: { when: "check" | "hit" | "dying" | "nat1"; line: string }[] = [];
  const ids = uniqueSpellIds(sheet);
  for (const id of ids) {
    const sp = spellById(id);
    if (!sp?.askOn) continue;
    out.push({
      when: sp.askOn,
      line: `${sheet.name} 的「${sp.name}」（${sp.level === 0 ? "戏法，不耗位" : `${sp.level} 环`}）：走掷骰勾选，不要口头再问。${sp.text}`,
    });
  }
  if (sheet.subclassId === "war") {
    out.push({
      when: "hit",
      line: `${sheet.name} 战争祭司：本回合用动作打过一次后，可用附赠再攻一次。次数＝感知调整（至少 1），长休恢复。第二下掷出才扣，排队或口头说不算。`,
    });
  }
  if (sheet.raceId === "lightfoot") {
    out.push({
      when: "nat1",
      line: `${sheet.name} 半身人幸运：d20 出 1 必须提醒可重掷，不耗资源`,
    });
  }
  if (sheet.classId === "rogue") {
    out.push({
      when: "check",
      line: `${sheet.name} 可用灵巧动作躲藏（附赠动作，不耗资源），隐匿检定前可问要不要先躲`,
    });
  }
  return out;
}
