type UnknownRecord = Record<string, unknown>;

export type CurrentDeliveryNarrationResult =
  | { kind: "unavailable" }
  | { kind: "synthesisFailed"; status?: number; empty?: true }
  | { kind: "audio"; bytes: Uint8Array; mime: string };

function record(value: unknown): UnknownRecord | undefined {
  return value !== null && typeof value === "object" && !Array.isArray(value)
    ? value as UnknownRecord
    : undefined;
}

function currentFrame(observation: unknown, deliveryId: string) {
  const delivery = record(record(observation)?.delivery);
  const frame = delivery?.kind === "current" ? record(delivery.frame) : undefined;
  return frame?.deliveryId === deliveryId
    && typeof frame.payloadHash === "string"
    && typeof frame.text === "string"
    ? {
        deliveryId,
        payloadHash: frame.payloadHash,
        text: frame.text,
      }
    : undefined;
}

/**
 * Server-side TTS is a presentation of one current DeliveryFrame, not a media
 * archive. Re-observing after the external synthesis call closes the ACK,
 * overwrite, and control-revocation race before any generated bytes leave the
 * Worker.
 */
export async function synthesizeCurrentDeliveryNarration(input: {
  messageId: string;
  observe(query: {
    channel: "voice";
    referenceId: string;
  }): Promise<unknown>;
  synthesize(text: string): Promise<Response>;
}): Promise<CurrentDeliveryNarrationResult> {
  const query = { channel: "voice" as const, referenceId: input.messageId };
  const before = currentFrame(await input.observe(query), input.messageId);
  if (before === undefined) return { kind: "unavailable" };

  const response = await input.synthesize(before.text.slice(0, 800));
  if (!response.ok) return { kind: "synthesisFailed", status: response.status };
  const bytes = new Uint8Array(await response.arrayBuffer());
  if (bytes.length === 0) return { kind: "synthesisFailed", empty: true };

  const after = currentFrame(await input.observe(query), input.messageId);
  if (
    after === undefined
    || after.deliveryId !== before.deliveryId
    || after.payloadHash !== before.payloadHash
  ) {
    return { kind: "unavailable" };
  }

  const contentType = response.headers.get("content-type")?.split(";")[0];
  return {
    kind: "audio",
    bytes,
    mime: contentType?.startsWith("audio/") ? contentType : "audio/mpeg",
  };
}
